# Generated by Django 4.2.4 on 2023-09-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="body",
            field=models.TextField(verbose_name="review"),
        ),
    ]
