# Generated by Django 4.2.4 on 2023-09-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
